---

dist: trusty
language: python
python: "2.7"

sudo: false

# Install ansible.
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible.
  - pip install ansible
  - pip install ansible-lint
  - pip install ansible-review

  # Check ansible version.
  - ansible --version
  - ansible-lint --version
  - ansible-review --version

  # Create ansible.cfg with correct roles_path.
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-lint -v tasks/main.yml
  - git ls-files | grep yml | xargs ansible-review -q

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
