---

- import_tasks: windows/ciphers.yml

- import_tasks: windows/hashes.yml

- import_tasks: windows/protocols.yml

# Regedit to add "SchUseStrongCrypto" key
- name: "Add SchUseStrongCrypto key to Wow6432Node"
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319
    name: SchUseStrongCrypto
    data: 1
    type: dword
    state: "{{ (schannel_usestrongcrypto|bool)|ternary('present','absent') }}"

- name: "Add SchUseStrongCrypto key to Microsoft .NET Framework"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319
    name: SchUseStrongCrypto
    data: 1
    type: dword
    state: "{{ (schannel_usestrongcrypto|bool)|ternary('present','absent') }}"

# https://docs.microsoft.com/en-us/security-updates/SecurityAdvisories/2016/3174644
- name: "Update Diffie-Hellman Key Exchange DH modulus minimum."
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms
    name: Diffie-Hellman
    data: "{{ [ schannel_dhmodulus ]|map('extract', {'1024': '00000400', '2048': '00000800', '3072': '00000C00', '4096': '00001000'})|first }}"
    type: dword
    state: present
