---

- import_tasks: windows/ciphers.yml

- import_tasks: windows/hashes.yml

- import_tasks: windows/protocols.yml

# Regedit to add "SchUseStrongCrypto" key
- name: "Add SchUseStrongCrypto key to Wow6432Node"
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319
    name: SchUseStrongCrypto
    data: 1
    type: dword
    state: "{{ (schannel_usestrongcrypto|bool)|ternary('present','absent') }}"

- name: "Add SchUseStrongCrypto key to Microsoft .NET Framework"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319
    name: SchUseStrongCrypto
    data: 1
    type: dword
    state: "{{ (schannel_usestrongcrypto|bool)|ternary('present','absent') }}"
