---

# Cleanup nested SCHANNEL folders.

- name: Remove AES 128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 128
    delete_key: yes
    state: absent

- name: Remove AES 256.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 256
    delete_key: yes
    state: absent

- name: Remove DES 56.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\DES 56
    delete_key: yes
    state: absent

- name: Remove RC2 128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 128
    delete_key: yes
    state: absent

- name: Remove RC2 40.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 40
    delete_key: yes
    state: absent

- name: Remove RC2 56.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 56
    delete_key: yes
    state: absent

- name: Remove RC4 128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 128
    delete_key: yes
    state: absent

- name: Remove RC4 40.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 40
    delete_key: yes
    state: absent

- name: Set RC4 56.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 56
    delete_key: yes
    state: absent

- name: Remove RC4 64.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 64
    delete_key: yes
    state: absent

# Without creating registry keys first, win_regedit will nest the part after the
# forward slash in each cipher as another folder instead of part of the name.
# https://stackoverflow.com/questions/44067327/escaping-slash-in-a-win-regedit-path-on-ansible

- name: Set AES 128/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 128/128
    name: Enabled
    type: dword
    data: "{{ (schannel_aes_128|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set AES 256/256.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 256/256
    name: Enabled
    type: dword
    data: "{{ (schannel_aes_256|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set NULL ciphers.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\NULL
    name: Enabled
    type: dword
    data: "{{ (schannel_null|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set DES 56/56.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\DES 56/56
    name: Enabled
    type: dword
    data: "{{ (schannel_des|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set RC2 128/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 128/128
    name: Enabled
    type: dword
    data: "{{ (schannel_rc2|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set RC2 40/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 40/128
    name: Enabled
    type: dword
    data: "{{ (schannel_rc2|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set RC2 56/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 56/128
    name: Enabled
    type: dword
    data: "{{ (schannel_rc2|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set RC4 128/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 128/128
    name: Enabled
    type: dword
    data: "{{ (schannel_rc4|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set RC4 40/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 40/128
    name: Enabled
    type: dword
    data: "{{ (schannel_rc4|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set RC4 56/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 56/128
    name: Enabled
    type: dword
    data: "{{ (schannel_rc4|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set RC4 64/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 64/128
    name: Enabled
    type: dword
    data: "{{ (schannel_rc4|bool)|ternary('4294967295','0') }}"
    state: present

# Triple DES needs special handling since it changed from 2008/7 to 2012/8/10.

- block:

  - name: Remove Triple DES 168.
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168
      delete_key: yes
      state: absent

  - name: "Create cipher registry keys."
    win_shell: "$path=new-item -path 'HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers';$key = (get-item HKLM:\\).OpenSubKey('System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers', $true);$key.CreateSubKey('{{ item }}');$key.Close()"
    with_items:
      - "Triple DES 168/168"

  - name: Set Triple DES 168/168.
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168/168
      name: Enabled
      type: dword
      data: "{{ (schannel_3des|bool)|ternary('4294967295','0') }}"
      state: present

  when: ansible_os_name | search("Windows Server 2008") or ansible_os_name | search("Windows 7")

- name: Set Triple DES 168.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168
    name: Enabled
    type: dword
    data: "{{ (schannel_3des|bool)|ternary('4294967295','0') }}"
    state: present
  when: not ansible_os_name | search("Windows Server 2008") and not ansible_os_name | search("Windows 7")
