---

# Cleanup nested SCHANNEL folders.

- name: Remove nested AES 128/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 128/128
    state: absent

- name: Remove nested AES 256/256.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 256/256
    state: absent

- name: Remove nested Triple DES 168/168.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168/168
    state: absent

- name: Remove nested NULL ciphers.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\NULL
    state: absent

- name: Remove nested DES 56/56.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\DES 56/56
    state: absent

- name: Remove nested RC2 128/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 128/128
    state: absent

- name: Remove nested RC2 40/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 40/128
    state: absent

- name: Remove nested RC2 56/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 56/128
    state: absent

- name: Remove nested RC4 128/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 128/128
    state: absent

- name: Remove nested RC4 40/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 40/128
    state: absent

- name: Set RC4 56/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 56/128
    state: absent

- name: Remove nested RC4 64/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 64/128
    state: absent

# Without creating registry keys first, win_regedit will nest the part after the
# forward slash in each cipher as another folder instead of part of the name.
# https://stackoverflow.com/questions/44067327/escaping-slash-in-a-win-regedit-path-on-ansible
- name: "Create cipher registry keys."
  win_shell: "$path=new-item -path 'HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers';$key = (get-item HKLM:\\).OpenSubKey('System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers', $true);$key.CreateSubKey('{{ item }}');$key.Close()"
  with_items:
    - "AES 128/128"
    - "AES 256/256"
    - "Triple DES 168/168"
    - "DES 56/56"
    - "RC2 128/128"
    - "RC2 40/128"
    - "RC2 56/128"
    - "RC4 128/128"
    - "RC4 40/128"
    - "RC4 56/128"
    - "RC4 64/128"

- name: Set AES 128/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 128/128
    name: Enabled
    type: dword
    data: "{{ (schannel_aes_128|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set AES 256/256.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 256/256
    name: Enabled
    type: dword
    data: "{{ (schannel_aes_256|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set Triple DES 168/168.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168/168
    name: Enabled
    type: dword
    data: "{{ (schannel_3des|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set NULL ciphers.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\NULL
    name: Enabled
    type: dword
    data: "{{ (schannel_null|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set DES 56/56.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\DES 56/56
    name: Enabled
    type: dword
    data: "{{ (schannel_des|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set RC2 128/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 128/128
    name: Enabled
    type: dword
    data: "{{ (schannel_rc2|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set RC2 40/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 40/128
    name: Enabled
    type: dword
    data: "{{ (schannel_rc2|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set RC2 56/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 56/128
    name: Enabled
    type: dword
    data: "{{ (schannel_rc2|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set RC4 128/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 128/128
    name: Enabled
    type: dword
    data: "{{ (schannel_rc4|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set RC4 40/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 40/128
    name: Enabled
    type: dword
    data: "{{ (schannel_rc4|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set RC4 56/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 56/128
    name: Enabled
    type: dword
    data: "{{ (schannel_rc4|bool)|ternary('4294967295','0') }}"
    state: present

- name: Set RC4 64/128.
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 64/128
    name: Enabled
    type: dword
    data: "{{ (schannel_rc4|bool)|ternary('4294967295','0') }}"
    state: present
